ppa_repositories:
  - name: ppa:ansible/ansible
    creates: ansible-ansible-trusty.list
  - name: ppa:fish-shell/release-2
    creates: fish-shell-release-2-trusty.list
  - name: ppa:kxstudio-debian/kxstudio
    creates: kxstudio-debian.list
  - name: ppa:klaus-vormweg/ppa
    creates: klaus-vormweg-ppa-trusty.list

deb_repositories:
  - name: deb http://archive.canonical.com/ trusty partner
  - name: deb http://debian.sur5r.net/i3/ trusty universe

repository_packages:
  - name: kxstudio-repos
  - name: sur5r-keyring

pretask_packages:
  - name: python-apt
  - name: python-pycurl
  - name: software-properties-common
