- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: install repository packages
  sudo: yes
  with_items: repository_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: update all packages to the latest version
  sudo: yes
  apt:
    upgrade: dist

- name: install packages
  sudo: yes
  with_items: common_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: restart openntpd
  sudo: yes
  service:
    name: openntpd
    enabled: yes
    state: restarted

- name: install pip3 packages
  sudo: yes
  with_items: pip3_packages
  pip:
    executable: pip3
    name: "{{ item.name }}"
    state: latest

- name: configure grub
  sudo: yes
  copy:
    src: grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
  notify:
    - update grub
