- name: update apt
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install repository packages
  sudo: yes
  with_items: repository_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
    force: yes

- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: update all packages to the latest version
  sudo: yes
  apt:
    upgrade: dist

- name: install packages
  sudo: yes
  with_items: common_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
  notify:
    - restart openntpd

- name: install pip3 packages
  sudo: yes
  with_items: pip3_packages
  pip:
    executable: pip3
    name: "{{ item.name }}"
    state: latest

- name: configure grub
  sudo: yes
  copy:
    src: grub
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0644
  notify:
    - update grub

#- name: update apt-file
#  sudo: yes
#  command: apt-file update

- name: disable system wide mpd
  sudo: yes
  service:
    name: mpd
    enabled: no
    state: stopped
