- name: Install local ansible data path directory
  tags: maven
  sudo: yes
  file:
    state=directory
    mode=2777
    dest={{ data_path }}


- name: Download Maven
  tags: maven
  sudo: no
  get_url:
    dest={{ data_path }}/{{ maven_filename }}
    url={{ maven_mirror }}/{{ maven_filename }}
    mode=0644
    sha256sum={{ maven_checksum }}

