# Main list of tasks to be executed.

- name: Load version vars
  tags: maven
  with_first_found:
    - ../vars/versions/{{ maven_version }}.yml
  include_vars: "{{ item }}"

- include: local.yml
  tags: maven

- name: Install remote ansible data path directory
  tags: maven
  sudo: yes
  file:
    state=directory
    dest={{ data_path }}

- name: Install Maven installation directory
  tags: maven
  sudo: yes
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ maven_install_dir }}


- name: Install Maven
  tags: maven
  sudo: yes
  unarchive:
    src={{ data_path }}/{{ maven_filename }}
    dest={{ maven_install_dir }}
    copy=false
    creates={{ maven_install_dir }}/apache-maven-{{ maven_version }}


- name: Install Maven bin directory
  tags: maven
  sudo: yes
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ maven_bin_path }}


- name: Install Maven binary
  tags: maven
  sudo: yes
  file:
    state=link
    force=true
    src={{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvn
    dest={{ maven_bin_path }}/mvn
