- name: add users
  sudo: yes
  user:
    name: "meka"
    shell: "/usr/bin/fish"

- name: configure cron for meka
  sudo: yes
  sudo_user: meka
  cron:
    name: run ~/bin stuf
    state: present
    job: ~/bin/cron.sh
    minute: "*/3"
