- name: add users
  sudo: yes
  user:
    name: "mladen"
    shell: "/usr/bin/zsh"
    groups: "audio,video,sudo"
    append: yes

- name: configure cron for mladen
  sudo: yes
  sudo_user: mladen
  cron:
    name: run ~/bin stuf
    state: present
    job: ~/bin/cron.sh
    minute: "*"

- name: install vex
  sudo: yes
  sudo_user: mladen
  pip:
    name: vex
    extra_args: "--user"
    state: present

- name: download rofi
  sudo: yes
  sudo_user: mladen
  git:
    repo: https://github.com/DaveDavenport/rofi
    dest: ~/rofi
    accept_hostkey: yes
    depth: 1

- name: autoreconfigure rofi
  sudo: yes
  sudo_user: mladen
  command: autoreconf -i
  args:
    chdir: ~/rofi
    creates: ~/rofi/configure

- name: configure rofi
  sudo: yes
  sudo_user: mladen
  command: ./configure
  args:
    chdir: ~/rofi
    creates: ~/rofi/rofi

- name: make rofi
  sudo: yes
  sudo_user: mladen
  command: make
  args:
    chdir: ~/rofi
    creates: ~/rofi/rofi

- name: make install rofi
  sudo: yes
  command: make install
  args:
    chdir: ~mladen/rofi
    creates: /usr/local/bin/rofi

- name: ensure ~/Files exists
  sudo: yes
  sudo_user: mladen
  file:
    path: ~/Files
    state: directory

- name: ensure ~/Files/repos exists
  sudo: yes
  sudo_user: mladen
  file:
    path: ~/Files/repos
    state: directory

- name: configure git
  sudo: yes
  sudo_user: mladen
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
