- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: install packages
  sudo: yes
  with_items: pretask_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: add repositories
  sudo: yes
  with_items: repositories
  apt_repository:
    repo: "{{ item.name }}"
    state: absent
