- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: install packages
  sudo: yes
  with_items: pretask_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: add i386 architecture
  sudo: yes
  command: dpkg --add-architecture i386

- name: add repositories
  sudo: yes
  with_items: repositories
  command: add-apt-repository -y "{{ item.name }}"
