development_packages:
  - name: oracle-java7-installer
  - name: oracle-java7-set-default
  - name: mysql-server
  - name: mysql-workbench
  - name: kdiff3

ppa_repositories:
  - name: ppa:webupd8team/java
    creates: oracle-java8-installer.list

